[project]
name = "fuzzy-flash"
authors = ["Your Name"]
description = "A decentralized platform for secure, privacy-preserving health data management"
telemetry = false
requirements = []
[contracts.biometric-access-registry]
path = "contracts/biometric-access-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
